## Conda environment for the course "Statistical Analysis with R" 
## of the "Diplome Universitaire en Bioinformatique integrative" (DU-Bii).
## https://du-bii.github.io/accueil/
name: dubii19-m3-stat-r

channels:
  - r
  - conda-forge
  - bioconda
  - lcantini

dependencies:

  ## RCRAN packages
  - r::r-base  >=3.5,< 3.6
  - r::r-e1071 
  - r::r-randomforest
  - r::r-yaml        # Required to load the config file
  - r::r-roxygen2    # To build the package doc
  - r::r-kableextra    # To export nice-looking tables in the R markdown reports
  - bioconda::r-mixomics # For the course of integrative bioinformatics
  
  ## Bioconductor packages
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-edger 
  - bioconda::bioconductor-limma
  
  ## Other packages
  - lcantini::r-mofa
