## Conda environment for the course "Statistical Analysis with R" 
## of the "Diplome Universitaire en Bioinformatique integrative" (DU-Bii).
## https://du-bii.github.io/accueil/
name: dubii_r_2019

channels:
  - r
  - conda-forge
  - bioconda
  - lcantini

dependencies:

  ## RCRAN packages
  - r::r-base  >=3.5,< 3.6
  - r::r-knitr        # For R markdown
  - r::r-kableextra   # To export nice-looking tables in the R markdown reports
  - r::r-formattable  # nice formating of tables in reports
  - r::r-roxygen2     # To build package documentation
  - r::r-yaml         # Required to load Yaml config files
  - r::r-e1071        # for SVM
  - r::r-randomforest # Supervised classification
  
  ## Bioconductor packages
  - bioconda::bioconductor-deseq2
  - bioconda::bioconductor-edger 
  - bioconda::bioconductor-limma
  - bioconda::r-mixomics # For the course of integrative bioinformatics
  
  ## Other packages
  - lcantini::r-mofa
